import { Email } from './types';

export const MOCK_EMAILS: Email[] = [
  {
    id: 'e1',
    sender: 'Boss',
    senderEmail: 'boss@company.com',
    subject: 'Q3 Report Deadline',
    snippet: 'Hey, just a reminder that the Q3 reports are due by EOD tomorrow. Please ensure...',
    date: '10:30 AM',
    isRead: false,
    isStarred: true,
    selected: false,
  },
  {
    id: 'e2',
    sender: 'Best Buy',
    senderEmail: 'marketing@bestbuy.com',
    subject: 'HUGE 48-Hour Sale! 50% Off Laptops',
    snippet: 'Don\'t miss out on these doorbuster deals. Click here to unsubscribe from future emails.',
    date: '9:15 AM',
    isRead: false,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e3',
    sender: 'Netflix',
    senderEmail: 'info@netflix.com',
    subject: 'Coming Soon: Season 5',
    snippet: 'See what\'s new on Netflix this month. Manage your subscription preferences here.',
    date: 'Yesterday',
    isRead: true,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e4',
    sender: 'Mom',
    senderEmail: 'mom@gmail.com',
    subject: 'Sunday Dinner?',
    snippet: 'Are you coming over this Sunday? I\'m making lasagna. Let me know!',
    date: 'Yesterday',
    isRead: true,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e5',
    sender: 'The Morning Brew',
    senderEmail: 'newsletter@morningbrew.com',
    subject: 'Market Recap: Tech stocks rally',
    snippet: 'Daily digest: What happened in the markets today. If you cannot read this email, view online.',
    date: 'Oct 24',
    isRead: true,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e6',
    sender: 'LinkedIn',
    senderEmail: 'notifications@linkedin.com',
    subject: 'You appeared in 5 searches this week',
    snippet: 'See who is looking at your profile. Unsubscribe settings available in footer.',
    date: 'Oct 23',
    isRead: false,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e7',
    sender: 'Jira',
    senderEmail: 'jira@atlassian.com',
    subject: '[PROJ-1023] Bug in production',
    snippet: 'James commented on PROJ-1023: We need to fix this ASAP. See the attached logs.',
    date: 'Oct 23',
    isRead: true,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e8',
    sender: 'Spotify',
    senderEmail: 'no-reply@spotify.com',
    subject: 'Your 2024 Wrapped is here',
    snippet: 'See your top songs of the year. To stop receiving these emails, click unsubscribe.',
    date: 'Oct 22',
    isRead: true,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e9',
    sender: 'AWS Billing',
    senderEmail: 'no-reply-aws@amazon.com',
    subject: 'Invoice Available',
    snippet: 'Your invoice for October 2024 is now available. Total amount: $45.20.',
    date: 'Oct 21',
    isRead: true,
    isStarred: false,
    selected: false,
  },
  {
    id: 'e10',
    sender: 'Old Navy',
    senderEmail: 'offers@oldnavy.com',
    subject: 'Super Cash is BACK!',
    snippet: 'Redeem your points now. Only valid for 24 hours. Click here to unsubscribe.',
    date: 'Oct 20',
    isRead: false,
    isStarred: false,
    selected: false,
  },
];